[tool.poetry]
name        = "DepthFlow"
version     = "2023.11.29"
description = "Image to 2.5D Parallax Effect Video"
authors     = ["Tremeschin <tremeschin@users.noreply.github.com>"]
license     = "AGPLv3-only"

[[tool.poetry.packages]]
include = "DepthFlow"

[tool.poetry.scripts]
depthflow = "DepthFlow.__main__:main"

[tool.poe.tasks]
_install_torch_cuda = "python -m pip install torch==2.0.1 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118"
_install_torch_rocm = "python -m pip install torch==2.0.1 torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm5.6"
_install_torch_cpu  = "python -m pip install torch==2.0.1 torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu"
_uninstall_torch    = "python -m pip uninstall -y torch torchvision torchaudio"
cuda                = ["_uninstall_torch", "_install_torch_cuda"]
rocm                = ["_uninstall_torch", "_install_torch_rocm"]
cpu                 = ["_uninstall_torch", "_install_torch_cpu"]

[build-system]
requires      = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python       = ">=3.10,<3.13"
broken       = {path="../../", develop=true}
shaderflow   = {path="../ShaderFlow", develop=true}
torch        = {version="2.0.1", source="torch-cpu"}
transformers = "^4.35.2"
timm         = "0.6.7"

[[tool.poetry.source]]
name     = "torch-cpu"
priority = "explicit"
url      = "https://download.pytorch.org/whl/cpu"

[[tool.poetry.source]]
name     = "torch-cuda"
priority = "explicit"
url      = "https://download.pytorch.org/whl/cu118"

[[tool.poetry.source]]
name     = "torch-rocm"
priority = "explicit"
url      = "https://download.pytorch.org/whl/rocm5.4.2"
